import { Trip } from '../types';

export const TRIPS: Trip[] = [
  // NORTH
  {
    id: 'n1',
    name: 'שמורת נחל שניר (חצבאני)',
    description: 'מסלול מים רענן ומוצל, מושלם לזוגות שאוהבים ללכת בתוך המים הקרירים.',
    region: 'north',
    style: 'water',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '2 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'הליכה קלה במים רדודים ועל גשרוני עץ.',
    travelTime: 'כשעתיים וחצי ממרכז הארץ',
    startPoint: 'חניון שמורת נחל שניר',
    endPoint: 'חניון שמורת נחל שניר',
    highlights: ['הליכה בתוך המים', 'עצי דולב ענקיים', 'פינות חמד מוצלות'],
    foodRecommendations: ['דג על הדן', 'פוקצ׳ה בגן'],
    whatToBring: ['נעליים להליכה במים', 'בגד ים', 'מגבת'],
    season: 'קיץ, אביב',
    bestTime: 'בוקר מוקדם',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=שמורת+נחל+שניר+חצבאני',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%A9%D7%9E%D7%95%D7%A8%D7%AA-%D7%98%D7%91%D7%A2-%D7%A0%D7%97%D7%9C-%D7%A9%D7%A0%D7%99%D7%A8-%D7%97%D7%A6%D7%91%D7%90%D7%A0%D7%99/',
    whyThisFits: 'השילוב של מים זורמים וצל הופך את זה לדייט מרענן ורומנטי במיוחד בקיץ הישראלי.',
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'n2',
    name: 'מצפה אופיר וטיילת דרום הגולן',
    description: 'תצפית פנורמית עוצרת נשימה על הכנרת והרי הגליל, מושלם לפיקניק שקיעה.',
    region: 'north',
    style: 'view',
    difficulty: 'easy',
    type: 'short',
    hasFood: false,
    timeAvailable: 'short',
    duration: 'שעה',
    distance: '1 ק"מ',
    trailType: 'קווי (הלוך חזור)',
    effortDescription: 'הליכה מישורית וקלה מאוד על קצה המצוק.',
    travelTime: 'כשעתיים מחיפה',
    startPoint: 'חניון מצפה אופיר',
    endPoint: 'מצפה אופיר',
    highlights: ['נוף מהפנט לכנרת', 'עצי זית עתיקים', 'שקיעות מדהימות'],
    foodRecommendations: ['מסעדות במעלה גמלא', 'קפה במצפה לשלום'],
    whatToBring: ['מחצלת פיקניק', 'ז׳קט (קריר בערב)', 'מצלמה'],
    season: 'כל השנה',
    bestTime: 'שקיעה',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=מצפה+אופיר',
    infoLink: 'https://www.tiuli.com/points-of-interest/184/מצפה-אופיר',
    whyThisFits: 'אין דבר רומנטי יותר מלראות את הכנרת נצבעת בכתום בזמן שאתם יושבים על המצוק.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'n3',
    name: 'נחל עמוד תחתון',
    description: 'טיול בין בוסתנים, טחנות קמח עתיקות ובריכות מים צלולות.',
    region: 'north',
    style: 'nature',
    difficulty: 'medium',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'half-day',
    duration: '3-4 שעות',
    distance: '4 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'ירידה תלולה בתחילת המסלול ועליה בסופו.',
    travelTime: 'שעתיים ממרכז הארץ',
    startPoint: 'חניון נחל עמוד (ליד צפת)',
    endPoint: 'חניון נחל עמוד',
    highlights: ['בריכות שקווי', 'טחנות קמח', 'עצי פרי'],
    foodRecommendations: ['מסעדות בצפת העתיקה', 'חומוס באבו אדהם'],
    whatToBring: ['נעלי הליכה טובות', 'מים', 'בגד ים'],
    season: 'סתיו, אביב',
    bestTime: 'בוקר',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=חניון+נחל+עמוד',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%A9%D7%9E%D7%95%D7%A8%D7%AA-%D7%98%D7%91%D7%A2-%D7%A0%D7%97%D7%9C-%D7%A2%D7%9E%D7%95%D7%94/',
    whyThisFits: 'הליכה שקטה בטבע פראי עם נקודות עצירה קרירות במים.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'n4',
    name: 'ראש הנקרה',
    description: 'נקרות ימיות מרהיבות שנחצבו בסלע הגיר הלבן על ידי הים.',
    region: 'north',
    style: 'romantic',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '1 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'ירידה ברכבל והליכה על שבילים מוסדרים.',
    travelTime: 'שעה וחצי מחיפה',
    startPoint: 'אתר ראש הנקרה',
    endPoint: 'אתר ראש הנקרה',
    highlights: ['נקרות כחולות', 'נסיעה ברכבל', 'גבול לבנון'],
    foodRecommendations: ['מסעדות בנהריה', 'דגי בננה'],
    whatToBring: ['מצלמה', 'נעליים נוחות'],
    season: 'כל השנה',
    bestTime: 'לפני הצהריים',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=ראש+הנקרה',
    infoLink: 'https://www.tiuli.com/points-of-interest/4/%D7%A8%D7%90%D7%A9-%D7%94%D7%A0%D7%A7%D7%A8%D7%94',
    whyThisFits: 'הצבע הכחול של המים והסלעים הלבנים יוצרים תפאורה מושלמת לתמונות זוגיות.',
    imageUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f45d8de4?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'n5',
    name: 'נחל כזיב ועין חרדלית',
    description: 'הליכה קלילה וכיפית במים רדודים, מתאים מאוד לימים חמים.',
    region: 'north',
    style: 'water',
    difficulty: 'easy',
    type: 'short',
    hasFood: false,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '2 ק"מ',
    trailType: 'קווי',
    effortDescription: 'מישור, הליכה בתוך המים.',
    travelTime: 'חצי שעה מנהריה',
    startPoint: 'חניון עין חרדלית',
    endPoint: 'עין חרדלית',
    highlights: ['מים זורמים', 'צל כבד', 'הרבה פרפרים'],
    foodRecommendations: ['מסעדות במעיליא', 'קפה במצפה הילה'],
    whatToBring: ['סנדלי הליכה', 'בגד ים'],
    season: 'קיץ',
    bestTime: 'אמצע שבוע',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=עין+חרדלית',
    infoLink: 'https://www.tiuli.com/points-of-interest/12/עין-חרדלית',
    whyThisFits: 'מסלול רטוב, כיפי ולא מחייב.',
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'n6',
    name: 'הר מירון - שביל הפסגה',
    description: 'מסלול מעגלי קצר סביב פסגת המירון עם תצפיות לכל עבר.',
    region: 'north',
    style: 'view',
    difficulty: 'easy',
    type: 'circular',
    hasFood: false,
    timeAvailable: 'short',
    duration: 'שעה וחצי',
    distance: '1.5 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'מישור ברובו, שביל מוסדר.',
    travelTime: 'חצי שעה מצפת',
    startPoint: 'חניון הפסגה, הר מירון',
    endPoint: 'חניון הפסגה',
    highlights: ['נוף ללבנון ולכנרת', 'חורש ים תיכוני עשיר', 'אוויר הרים'],
    foodRecommendations: ['אוכל דרוזי בחורפיש', 'עספיא'],
    whatToBring: ['בגדים חמים (גם בקיץ)', 'מים'],
    season: 'כל השנה (בחורף יש סיכוי לשלג)',
    bestTime: 'בוקר או שקיעה',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=חניון+הפסגה+הר+מירון',
    infoLink: 'https://www.parks.org.il/trip/meiron/',
    whyThisFits: 'הליכה שלווה בין העננים עם נוף שמשתנה בכל פניה.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  },

  // CENTER
  {
    id: 'c1',
    name: 'נחל אלכסנדר - גשר הצבים',
    description: 'הליכה נעימה לצד הנחל וצפייה בצבי מים רכים ענקיים.',
    region: 'center',
    style: 'nature',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעה וחצי',
    distance: '3 ק"מ',
    trailType: 'קווי',
    effortDescription: 'מישור מוחלט, שביל סלול בחלקו.',
    travelTime: 'חצי שעה מתל אביב',
    startPoint: 'חניון גשר הצבים',
    endPoint: 'שפך הנחל (חוף בית ינאי)',
    highlights: ['צבים רכים', 'פריחה עונתית', 'סיום בים'],
    foodRecommendations: ['קפה בקניון אם הדרך', 'ויטרינה בבית ינאי'],
    whatToBring: ['כובע', 'קרם הגנה', 'מים'],
    season: 'חורף, אביב',
    bestTime: 'אחר הצהריים',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=גשר+הצבים+נחל+אלכסנדר',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%92%D7%9F-%D7%9C%D7%90%D7%95%D7%9D%D7%99-%D7%A0%D7%97%D7%9C-%D7%90%D7%9C%D7%9B%D7%A1%D7%A0%D7%93%D7%A8/',
    whyThisFits: 'טיול קליל ורומנטי שמשלב נחל וים במינימום מאמץ.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'c2',
    name: 'גן לאומי אפולוניה',
    description: 'סיור בין שרידי מבצר צלבני עתיק על מצוק מעל הים בהרצליה.',
    region: 'center',
    style: 'romantic',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '1.5 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'הליכה קלה באתר ארכיאולוגי מונגש.',
    travelTime: '15 דקות מהרצליה',
    startPoint: 'כניסה לאתר אפולוניה',
    endPoint: 'כניסה לאתר אפולוניה',
    highlights: ['מצודה עתיקה', 'נוף לים התיכון', 'ספסלים מול הגלים'],
    foodRecommendations: ['מסעדות במרינה הרצליה', 'בנדיקט הירוק'],
    whatToBring: ['מים', 'מצלמה'],
    season: 'כל השנה',
    bestTime: 'שקיעה',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=גן+לאומי+אפולוניה',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%92%D7%9F-%D7%9C%D7%90%D7%95%D7%9D%D7%99-%D7%AA%D7%9C-%D7%90%D7%A4%D7%95%D7%9C%D7%95%D7%A0%D7%99%D7%94/',
    whyThisFits: 'הרומנטיקה של פעם פוגשת את הים - אתר מושלם להצעות נישואין או סתם ערב שקט.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'c3',
    name: 'פארק אלונה - מי קדם',
    description: 'חוויה ייחודית של הליכה בתוך נקבת מים עתיקה מהתקופה הרומית.',
    region: 'center',
    style: 'water',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעה וחצי',
    distance: '0.5 ק"מ',
    trailType: 'קווי בתוך נקבה',
    effortDescription: 'הליכה במים (עד גובה המותניים), מקום סגור וחשוך מעט.',
    travelTime: '45 דקות מתל אביב',
    startPoint: 'אתר מי קדם (ליד עמיקם)',
    endPoint: 'אתר מי קדם',
    highlights: ['הליכה בנקבה חשוכה', 'מים צלולים', 'היסטוריה חיה'],
    foodRecommendations: ['יקבים בבנימינה', 'מסעדות בזכרון יעקב'],
     whatToBring: ['נעליים למים', 'בגדים להחלפה', 'פנס (אופציונלי)'],
    season: 'קיץ, אביב',
    bestTime: 'צהריים (קריר בתוך הנקבה)',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=מי+קדם+פארק+אלונה',
    infoLink: 'https://www.mey-kedem.co.il/',
    whyThisFits: 'קצת הרפתקנות בתוך המים - חוויה זוגית מצחיקה ומרעננת.',
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'c4',
    name: 'יער בן שמן - מצפה מודיעין',
    description: 'טיול ביער הגדול במרכז עם פינות פיקניק ותצפיות נוף.',
    region: 'center',
    style: 'nature',
    difficulty: 'easy',
    type: 'circular',
    hasFood: false,
    timeAvailable: 'half-day',
    duration: '2-3 שעות',
    distance: '5 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'שינויי גובה קלים, שבילי יער.',
    travelTime: '20 דקות ממודיעין',
    startPoint: 'מצפה מודיעין',
    endPoint: 'מצפה מודיעין',
    highlights: ['נוף לירושלים ותל אביב', 'פריחת רקפות בחורף', 'שקט'],
    foodRecommendations: ['קפה משאית בכפר דניאל', 'מודיעין סנטר'],
    whatToBring: ['נעלי הליכה', 'מחצלת'],
    season: 'חורף, אביב',
    bestTime: 'בוקר שבת',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=מצפה+מודיעין',
    infoLink: 'https://www.kkl.org.il/forestsearch/ben_shemen_forest.aspx',
    whyThisFits: 'הריאה הירוקה של המרכז - מקום מושלם לברוח מהעיר.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'c5',
    name: 'שמורת חוף השרון',
    description: 'צוקי כורכר מעל הים, צמחיית חוף ייחודית ותצפיות מרהיבות.',
    region: 'center',
    style: 'sunset',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעה וחצי',
    distance: '2 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'הליכה חולית קלה.',
    travelTime: '10 דקות משפיים',
    startPoint: 'חניון שמורת חוף השרון',
    endPoint: 'חניון שמורת חוף השרון',
    highlights: ['מצוקי כורכר', 'ים פתוח', 'פריחה'],
    foodRecommendations: ['קניון שפיים', 'מסעדות בנווה איתמר'],
    whatToBring: ['מים', 'כובע'],
    season: 'כל השנה',
    bestTime: 'שקיעה',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=שמורת+חוף+השרון',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%A9%D7%9E%D7%95%D7%A8%D7%AA-%D7%98%D7%91%D7%A2-%D7%97%D7%95%D7%A3-%D7%94%D7%A9%D7%A8%D7%95%D7%9F/',
    whyThisFits: 'אחד המקומות המיוחדים במישור החוף לצפייה בשקיעה.',
    imageUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f45d8de4?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'c6',
    name: 'מקורות הירקון - תל אפק',
    description: 'פארק רחב ידיים עם אגם, מבצר עתיק וצמחיית נחלים.',
    region: 'center',
    style: 'nature',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'half-day',
    duration: '2-3 שעות',
    distance: '3 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'מדשאות ושבילים נוחים.',
    travelTime: '15 דקות מפתח תקווה',
    startPoint: 'גן לאומי ירקון - תל אפק',
    endPoint: 'תל אפק',
    highlights: ['מבצר אנטיפטריס', 'בריכת הנופרים', 'נחל זורם'],
    foodRecommendations: ['מסעדות בהוד השרון', 'פיקניק בפארק'],
    whatToBring: ['ספר טוב', 'מחצלת'],
    season: 'כל השנה',
    bestTime: 'בוקר שבת',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=גן+לאומי+ירקון+תל+אפק',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%92%D7%9F-%D7%9C%D7%90%D7%95%D7%9D%D7%99-%D7%99%D7%A8%D7%A7%D7%9F-%D7%AA%D7%9C-%D7%90%D7%A4%D7%A7/',
    whyThisFits: 'פארק רגוע עם המון פינות שקטות לשיחה זוגית.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200&auto=format&fit=crop'
  },

  // JERUSALEM
  {
    id: 'j1',
    name: 'עין חנדק וסטף',
    description: 'טיול נופים בהרי ירושלים הכולל מעיינות נקבה וטרסות חקלאיות עתיקות.',
    region: 'jerusalem',
    style: 'nature',
    difficulty: 'medium',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'half-day',
    duration: '3 שעות',
    distance: '4 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'עליות וירידות במדרגות סלע.',
    travelTime: '20 דקות מירושלים',
    startPoint: 'חניון הסטף (עליון)',
    endPoint: 'חניון הסטף',
    highlights: ['מעיין נקבה', 'בוסתנים', 'נוף להרי ירושלים'],
    foodRecommendations: ['קפה בסטף', 'מסעדות בעין כרם'],
    whatToBring: ['נעלי הליכה', 'פנס לנקבה', 'מים'],
    season: 'כל השנה',
    bestTime: 'בוקר או אחר הצהריים',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=סטף+חניון+עליון',
    infoLink: 'https://www.kkl.org.il/forestsearch/sataf_forest.aspx',
    whyThisFits: 'שילוב של אוויר הרים צלול, מים קרירים ונוף גלילי באמצע הרי ירושלים.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'j2',
    name: 'עין כרם - שביל הכפר',
    description: 'סיור רומנטי בסמטאות הציוריות של עין כרם, בין כנסיות, גלריות ובתי קפה.',
    region: 'jerusalem',
    style: 'romantic',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '2 ק"מ',
    trailType: 'סיבוב בסמטאות',
    effortDescription: 'הליכה ברחובות מרוצפים, יש עליות.',
    travelTime: '10 דקות מירושלים',
    startPoint: 'רחוב המעיין, עין כרם',
    endPoint: 'מרכז הכפר',
    highlights: ['מעיין מרים', 'כנסיות מרשימות', 'חנויות בוטיק'],
    foodRecommendations: ['כרמא', 'בראסי', 'גלידה גולדה המקורית'],
    whatToBring: ['נעליים נוחות', 'מצלמה'],
    season: 'כל השנה',
    bestTime: 'שישי בבוקר או ערב',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=עין+כרם+ירושלים',
    infoLink: 'https://www.itraveljerusalem.com/he/neighborhood/ein-karem/',
    whyThisFits: 'הכי קרוב לחו"ל שיש בארץ - הרגשה של כפר אירופאי קטן.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'j3',
    name: 'נחל חלילים',
    description: 'ירידה נעימה ממבשרת ציון אל ערוץ הנחל עם מערות חלילים מרשימות.',
    region: 'jerusalem',
    style: 'nature',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '2.5 ק"מ',
    trailType: 'קווי (או מעגלי דרך השכונה)',
    effortDescription: 'ירידה קלה, הליכה בשביל ברור.',
    travelTime: '5 דקות ממבשרת ציון',
    startPoint: 'רחוב השלום, מבשרת ציון',
    endPoint: 'סיבוב מוצא',
    highlights: ['מערות זקיפים', 'נוף לירושלים', 'פריחת שקדיות (בינואר)'],
    foodRecommendations: ['מסעדות בקניון הראל', 'יקב קסטל'],
    whatToBring: ['מים', 'פנס למערות'],
    season: 'חורף, אביב',
    bestTime: 'בוקר',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=נחל+חלילים+מבשרת+ציון',
    infoLink: 'https://www.eyarok.org.il/trip/nahal-halilim/',
    whyThisFits: 'מסלול הליכה קצר עם "בונוס" של מערות כיפיות בסוף.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'j4',
    name: 'פארק המסילה ירושלים',
    description: 'הליכה (או רכיבה) על תוואי רכבת ישן שהפך לפארק אורבני תוסס.',
    region: 'jerusalem',
    style: 'romantic',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעה-שעתיים',
    distance: 'עד 7 ק"מ',
    trailType: 'קווי',
    effortDescription: 'מישור מלא, סלול.',
    travelTime: 'ירושלים',
    startPoint: 'התחנה הראשונה',
    endPoint: 'שכונת מלחה',
    highlights: ['אווירה אורבנית', 'בתי קפה לאורך הדרך', 'ספסלי ספרייה'],
    foodRecommendations: ['מתחם התחנה הראשונה', 'פיצה פלורה'],
    whatToBring: ['נעלי הליכה/ריצה'],
    season: 'כל השנה',
    bestTime: 'ערב',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=התחנה+הראשונה+ירושלים',
    infoLink: 'https://www.itraveljerusalem.com/he/attraction/train-track-park/',
    whyThisFits: 'מסלול דייט קלאסי - הליכה, דיבורים וקפה בסוף.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'j5',
    name: 'שמורת המסרק',
    description: 'מסלול מעגלי קצר בתוך חורש אורנים עתיק עם תצפיות.',
    region: 'jerusalem',
    style: 'view',
    difficulty: 'easy',
    type: 'circular',
    hasFood: false,
    timeAvailable: 'short',
    duration: 'שעה',
    distance: '1.5 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'עליה קצרה בתחילה.',
    travelTime: '15 דקות ממחלף שורש',
    startPoint: 'חניון שמורת המסרק',
    endPoint: 'חניון שמורת המסרק',
    highlights: ['אורנים ענקיים', 'מערות בונקרים', 'נוף לשפלה'],
    foodRecommendations: ['מסעדות בשואבה', 'קפה בשוליים'],
    whatToBring: ['ז׳קט'],
    season: 'כל השנה',
    bestTime: 'צהריים (מוצל)',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=שמורת+המסרק',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%A9%D7%9E%D7%95%D7%A8%D7%AA-%D7%98%D7%91%D7%A2-%D7%94%D7%94%D7%9E%D7%A1%D7%A8%D7%A7/',
    whyThisFits: 'שקט ופרטיות בין העצים העתיקים.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'j6',
    name: 'נחל קטלב',
    description: 'מסלול יפהפה ומוצל היורד מבר בהר אל הנחל עם עצי קטלב אדומי גזע.',
    region: 'jerusalem',
    style: 'nature',
    difficulty: 'medium',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'half-day',
    duration: '3 שעות',
    distance: '3.5 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'ירידה ועליה משמעותית בסוף.',
    travelTime: '15 דקות מבית שמש',
    startPoint: 'חניון בר בהר',
    endPoint: 'חניון בר בהר',
    highlights: ['עצי קטלב', 'נוף משגע', 'תחנת רכבת ישנה'],
    foodRecommendations: ['מסעדת בר בהר', 'יקבים באזור'],
    whatToBring: ['מים', 'נעלי הליכה'],
    season: 'חורף, אביב, סתיו',
    bestTime: 'בוקר',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=חניון+בר+בהר',
    infoLink: 'https://www.parks.org.il/trip/katlav/',
    whyThisFits: 'אחד המסלולים היפים ביותר בהרי ירושלים.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200&auto=format&fit=crop'
  },

  // SOUTH
  {
    id: 's1',
    name: 'עין עבדת',
    description: 'טיול קניוני מרהיב בלב המדבר עם בריכות מים, מפל וקירות גיר לבנים.',
    region: 'south',
    style: 'nature',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '2 ק"מ',
    trailType: 'קווי',
    effortDescription: 'הליכה מישורית ברובה (יש אופציה למסלול עם סולמות).',
    travelTime: 'שעתיים וחצי ממרכז הארץ',
    startPoint: 'חניון תחתון עין עבדת',
    endPoint: 'חניון תחתון (או עליון עם הקפצה)',
    highlights: ['מפל גבוה', 'נשרים בשמיים', 'נווה מדבר'],
    foodRecommendations: ['פלאפל בנגב', 'חוות בודדים'],
    whatToBring: ['מים', 'כובע', 'קרם הגנה'],
    season: 'סתיו, חורף, אביב',
    bestTime: 'בוקר',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=עין+עבדת',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%92%D7%9F-%D7%9C%D7%90%D7%95%D7%9D%D7%99-%D7%A2%D7%99%D7%9F-%D7%A2%D7%91%D7%93%D7%AA/',
    whyThisFits: 'נווה מדבר קסום שמרגיש כמו סרט - השקט והנוף המדברי עושים את העבודה.',
    imageUrl: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 's2',
    name: 'מכתש רמון - המנסרה',
    description: 'תופעת טבע ייחודית של סלעי בזלת בצורת מנסרות לצד מסלול הליכה נוח.',
    region: 'south',
    style: 'view',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעה',
    distance: '1 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'הליכה קלה על שביל עץ מוסדר.',
    travelTime: 'שעתיים וחצי ממרכז הארץ',
    startPoint: 'חניון המנסרה (בתוך המכתש)',
    endPoint: 'חניון המנסרה',
    highlights: ['סלעים בצורת מנסרות', 'נוף למכתש רמון'],
    foodRecommendations: ['מסעדות במצפה רמון', 'חומוס אליהו'],
    whatToBring: ['מים', 'כובע'],
    season: 'חורף, סתיו',
    bestTime: 'אחר הצהריים',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=המנסרה+מכתש+רמון',
    infoLink: 'https://www.parks.org.il/trip/ramon-2/',
    whyThisFits: 'מקום קטן ומיוחד עם תחושה של כוכב לכת אחר.',
    imageUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f45d8de4?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 's3',
    name: 'נחל בוקק',
    description: 'מסלול מים מדברי קצר וזמין ליד מלונות ים המלח.',
    region: 'south',
    style: 'water',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '2 ק"מ',
    trailType: 'קווי',
    effortDescription: 'הליכה רטובה קלה.',
    travelTime: 'שעתיים מהמרכז',
    startPoint: 'חניון נחל בוקק',
    endPoint: 'נחל בוקק',
    highlights: ['מים זורמים במדבר', 'צמחיית קנה'],
    foodRecommendations: ['מסעדות בממתחם המלונות'],
    whatToBring: ['סנדלים למים'],
    season: 'כל השנה',
    bestTime: 'בוקר',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=נחל+בוקק',
    infoLink: 'https://www.eyarok.org.il/trip/nahal-bokek/',
    whyThisFits: 'דייט רטוב וקליל אחרי או לפני רחצה בים המלח.',
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 's4',
    name: 'הקניון האדום',
    description: 'מסלול הליכה בקניון צר של אבני חול אדומות מרהיבות ליד אילת.',
    region: 'south',
    style: 'nature',
    difficulty: 'easy',
    type: 'short',
    hasFood: false,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '1.5 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'הליכה בתוך קניון צר, יש כמה סולמות קטנים.',
    travelTime: 'חצי שעה מאילת',
    startPoint: 'חניון הקניון האדום',
    endPoint: 'חניון הקניון האדום',
    highlights: ['קירות אבן חול אדומים', 'צילומי "אינסטגרם" מושלמים'],
    foodRecommendations: ['מסעדות באילת'],
    whatToBring: ['הרבה מים', 'כובע'],
    season: 'חורף, סתיו',
    bestTime: 'בוקר',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=הקניון+האדום',
    infoLink: 'https://www.eyarok.org.il/trip/the-red-canyon/',
    whyThisFits: 'הצבעים והצורות של הסלע יוצרים חוויה ויזואלית בלתי נשכחת.',
    imageUrl: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 's5',
    name: 'מצד תמר ועין תמר',
    description: 'תצפית על הערבה ומסלול הליכה קצר בין בריכות.',
    region: 'south',
    style: 'view',
    difficulty: 'easy',
    type: 'short',
    hasFood: false,
    timeAvailable: 'short',
    duration: 'שעה',
    distance: '1 ק"מ',
    trailType: 'קווי',
    effortDescription: 'מישור.',
    travelTime: 'חצי שעה מצומת הערבה',
    startPoint: 'מצד תמר',
    endPoint: 'מעיין עין תמר',
    highlights: ['נוף ערבי', 'שקט מדברי'],
    foodRecommendations: ['קפה בעין תמר'],
    whatToBring: ['מים'],
    season: 'חורף',
    bestTime: 'אחר הצהריים',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=מצד+תמר',
    infoLink: 'https://www.eyarok.org.il/trip/metzad-tamar/',
    whyThisFits: 'פינה שקטה ולא מוכרת לשקט זוגי.',
    imageUrl: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 's6',
    name: 'הר סדום - תצפית המלח',
    description: 'עליה קצרה לתצפית מעל ים המלח והרי אדום.',
    region: 'south',
    style: 'sunset',
    difficulty: 'easy',
    type: 'short',
    hasFood: false,
    timeAvailable: 'short',
    duration: 'שעה',
    distance: '1 ק"מ',
    trailType: 'קווי',
    effortDescription: 'עליה קצרה תלולה.',
    travelTime: '15 דקות ממלונות עין בוקק',
    startPoint: 'חניון הר סדום',
    endPoint: 'תצפית המלח',
    highlights: ['נוף לים המלח', 'הרי אדום', 'שקיעה'],
    foodRecommendations: ['אוכל בים המלח'],
    whatToBring: ['מים', 'נעליים'],
    season: 'חורף, סתיו',
    bestTime: 'שקיעה',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=הר+סדום+תצפית+המלח',
    infoLink: 'https://www.eyarok.org.il/trip/mount-sodom/',
    whyThisFits: 'שקיעה מדברית מעל המקום הכי נמוך בעולם.',
    imageUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f45d8de4?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'n7',
    name: 'אגמון החולה',
    description: 'סיור טבע קסום סביב האגם, שבו אלפי ציפורים נודדות עוצרות למנוחה.',
    region: 'north',
    style: 'nature',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'half-day',
    duration: '3 שעות',
    distance: '8.5 ק"מ (אפשר באופניים)',
    trailType: 'מעגלי סביב האגם',
    effortDescription: 'מישור מוחלט, מתאים מאוד לאופניים או רכב חשמלי.',
    travelTime: 'שעתיים וחצי ממרכז הארץ',
    startPoint: 'מרכז המבקרים אגמון החולה',
    endPoint: 'מרכז המבקרים',
    highlights: ['צפייה בעגורים', 'נוף להר חרמון', 'טיול בעגלת מסתור'],
    foodRecommendations: ['קפה באגמון', 'מסעדות בראש פינה'],
    whatToBring: ['נעלי הליכה', 'מצלמה עם זום', 'מים'],
    season: 'סתיו, חורף, אביב',
    bestTime: 'בוקר מוקדם או שקיעה',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=אגמון+החולה',
    infoLink: 'https://www.agamon-hula.co.il/',
    whyThisFits: 'השקט של האגם בשקיעה עם אלפי הציפורים הוא חוויה רומנטית שאי אפשר לשכוח.',
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'n8',
    name: 'נחל השופט',
    description: 'מסלול מעגלי קסום וירוק כל השנה, נגיש ונוח מאוד להליכה זוגית איטית.',
    region: 'north',
    style: 'flowers',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעה וחצי',
    distance: '2 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'שביל סלול ברובו, קל מאוד.',
    travelTime: 'שעה מתל אביב',
    startPoint: 'חניון חרובים, נחל השופט',
    endPoint: 'חניון חרובים',
    highlights: ['מפלונים', 'טחנת קמח ישנה', 'יער עבות'],
    foodRecommendations: ['קפה בקיבוץ הזורע', 'מסעדות ביוקנעם'],
    whatToBring: ['נעליים נוחות', 'מים'],
    season: 'כל השנה (שיא בפריחה באביב)',
    bestTime: 'בוקר',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=נחל+השופט',
    infoLink: 'https://www.tiuli.com/tracks/67/%D7%A0%D7%97%D7%9C-%D7%94%D7%A9%D7%95%D7%A4%D7%98-%D7%9E%D7%A1%D7%9C%D7%95%D7%9C-%D7%9E%D7%A9%D7%A4%D7%97%D7%AA%D7%99-%D7%A0%D7%92%D7%99%D7%A9-%D7%95%D7%99%D7%A4%D7%94%D7%A4%D7%94',
    whyThisFits: 'מרגיש כמו יער קסום מהאגדות, מושלם לשיחות ארוכות בתוך הירוק.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'c7',
    name: 'יפו העתיקה והנמל',
    description: 'טיול אורבני רומנטי בסמטאות המזלות, גשר המשאלות וסיום בנמל יפו.',
    region: 'center',
    style: 'urban',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '2 ק"מ',
    trailType: 'עירוני',
    effortDescription: 'הליכה בסמטאות, כולל מדרגות.',
    travelTime: 'בתוך תל אביב',
    startPoint: 'כיכר קדומים, יפו העתיקה',
    endPoint: 'נמל יפו',
    highlights: ['סמטאות המזלות', 'גשר המשאלות', 'תצפית על קו החוף'],
    foodRecommendations: ['הזקן והים', 'מאפיית אבולעפיה', 'מסעדות בשוק הפשפשים'],
    whatToBring: ['נעליים נוחות', 'מצלמה'],
    season: 'כל השנה',
    bestTime: 'שקיעה וערב',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=יפו+העתיקה',
    infoLink: 'https://www.oldjaffa.co.il/',
    whyThisFits: 'השילוב של אבנים עתיקות ונוף לים הוא נוסחה מנצחת לדייט מושלם.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'c8',
    name: 'גן לאומי קיסריה',
    description: 'מסע בזמן בין שרידים רומיים מרשימים, נמל עתיק וחוף ים משגע.',
    region: 'center',
    style: 'history',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'half-day',
    duration: '3 שעות',
    distance: '3 ק"מ',
    trailType: 'מעגלי באתר ארכיאולוגי',
    effortDescription: 'הליכה באתר מוסדר.',
    travelTime: '45 דקות מתל אביב',
    startPoint: 'כניסה לגן לאומי קיסריה',
    endPoint: 'כניסה לגן לאומי קיסריה',
    highlights: ['היפודרום', 'התיאטרון הרומי', 'הנמל העתיק'],
    foodRecommendations: ['הלנה בנמל', 'מסעדות בנמל קיסריה'],
    whatToBring: ['כובע', 'קרם הגנה', 'בגד ים (לחוף הסמוך)'],
    season: 'כל השנה',
    bestTime: 'אחר הצהריים',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=גן+לאומי+קיסריה',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%92%D7%9F-%D7%9C%D7%90%D7%95%D7%9D%D7%99-%D7%A7%D7%99%D7%A1%D7%A8%D7%99%D7%93/',
    whyThisFits: 'להרגיש ברומא לכמה שעות, עם אווירה יוקרתית ונוף כחול של ים.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'j7',
    name: 'טיילת ארמון הנציב',
    description: 'התצפית המפורסמת ביותר בירושלים, צופה על העיר העתיקה, המדבר והרי מואב.',
    region: 'jerusalem',
    style: 'view',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעה וחצי',
    distance: '2 ק"מ',
    trailType: 'קווי (טיילות)',
    effortDescription: 'הליכה מישורית על טיילת סלולה.',
    travelTime: 'ירושלים',
    startPoint: 'טיילת האז, ירושלים',
    endPoint: 'טיילת גולדמן',
    highlights: ['נוף הר הבית', 'שקיעה מעל העיר העתיקה', 'מדשאות'],
    foodRecommendations: ['בתי קפה בשכונת ארנונה', 'מסעדות במרכז העיר'],
    whatToBring: ['ז׳קט (תמיד קריר שם בערב)', 'מצלמה'],
    season: 'כל השנה',
    bestTime: 'שקיעה',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=טיילת+ארמון+הנציב',
    infoLink: 'https://www.itraveljerusalem.com/he/attraction/haas-promenade/',
    whyThisFits: 'המקום הכי יפה לראות את ירושלים נצבעת בזהב בזמן השקיעה.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'j8',
    name: 'עמק הצבאים',
    description: 'פארק טבע עירוני מדהים בלב ירושלים שבו צבאים מסתובבים חופשי.',
    region: 'jerusalem',
    style: 'nature',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '2.5 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'הליכה קלה בשבילים מוסדרים.',
    travelTime: 'ירושלים',
    startPoint: 'כניסה לעמק הצבאים (ליד צומת פת)',
    endPoint: 'כניסה לעמק הצבאים',
    highlights: ['מפגש עם צבאים', 'אגם טבעי', 'שלכת יפה בסתיו'],
    foodRecommendations: ['בתי קפה בשכונת רסקו', 'קפה בקניון מלחה'],
    whatToBring: ['מים', 'משקפת'],
    season: 'כל השנה',
    bestTime: 'בוקר או סוף היום',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=עמק+הצבאים',
    infoLink: 'https://www.tiuli.com/points-of-interest/175/%D7%A2%D7%9E%D7%A7-%D7%94%D7%A6%D7%91%D7%90%D7%99%D7%9D',
    whyThisFits: 'פינה שקטה של טבע בתוך העיר הסואנת - חוויה אינטימית ומרגשת.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 's7',
    name: 'פארק תמנה - עמודי שלמה',
    description: 'נוף ירחי של אבני חול אדומות, שרידי מכרות נחושת עתיקים ועצמה מדברית.',
    region: 'south',
    style: 'history',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'half-day',
    duration: '3-4 שעות',
    distance: 'משתנה (טיול רכוב + הליכות קצרות)',
    trailType: 'מעגלי רכוב עם נקודות הליכה',
    effortDescription: 'הליכות קצרות ברובן.',
    travelTime: '20 דקות מאילת',
    startPoint: 'מרכז המבקרים פארק תמנה',
    endPoint: 'האגם (בסוף הפארק)',
    highlights: ['עמודי שלמה', 'הפטרייה', 'האגם המלאכותי'],
    foodRecommendations: ['מסעדת האגם (בתוך הפארק)'],
    whatToBring: ['המון מים', 'כובע', 'קרם הגנה'],
    season: 'סתיו, חורף, אביב',
    bestTime: 'בוקר מוקדם',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=פארק+תמנה',
    infoLink: 'https://www.parktimna.co.il/',
    whyThisFits: 'המקום מרגיש כמו גלאקסיה אחרת, השקט המוחלט של המדבר מחבר בין אנשים.',
    imageUrl: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 's8',
    name: 'עין גדי - נחל דוד',
    description: 'נווה מדבר קלאסי עם מפלים זורמים כל השנה, יעלים וצמחייה עשירה.',
    region: 'south',
    style: 'water',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '2 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'הליכה בשבילים מסומנים, יש עליות.',
    travelTime: 'שעתיים וחצי ממרכז הארץ',
    startPoint: 'כניסה לשמורה (נחל דוד)',
    endPoint: 'חניון עין גדי',
    highlights: ['מפל דוד', 'מפגש עם יעלים', 'נקודות רחצה במים'],
    foodRecommendations: ['מזנון עין גדי', 'מסעדות במלון עין גדי'],
    whatToBring: ['בגד ים', 'מים', 'מגבת'],
    season: 'כל השנה (עדיף לא בשיא הקיץ בצהריים)',
    bestTime: 'בוקר מוקדם',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=נחל+דוד+עין+גדי',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%A9%D7%9E%D7%95%D7%A8%D7%AA-%D7%98%D7%91%D7%A2-%D7%A2%D7%99%D7%9F-%D7%92%D7%94%D7%99/',
    whyThisFits: 'השילוב של המדבר הצהוב והמים הזורמים הוא מראה מרגש ומיוחד.',
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'n9',
    name: 'מבצר נמרוד',
    description: 'מבצר ימי-ביניימי ענק ושמור היטב השוכן על שלוחה של הר חרמון.',
    region: 'north',
    style: 'history',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '1.5 ק"מ',
    trailType: 'מעגלי באתר',
    effortDescription: 'הליכה באתר ארכיאולוגי, מעט עליות.',
    travelTime: 'שלוש שעות מהמרכז',
    startPoint: 'גן לאומי מבצר נמרוד',
    endPoint: 'גן לאומי מבצר נמרוד',
    highlights: ['מעברי סתרים', 'תצפית על עמק החולה', 'מגדלי שמירה'],
    foodRecommendations: ['מסעדות במג׳דל שמס', 'קפה במסעדה'],
    whatToBring: ['נעליים נוחות', 'פנס למעברים'],
    season: 'כל השנה (בחורף יכול להיות קר מאוד)',
    bestTime: 'בוקר או אחר הצהריים',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=מבצר+נמרוד',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%92%D7%9F-%D7%9C%D7%90%D7%95%D7%9D%D7%99-%D7%9E%D7%91%D7%A6%D7%A8-%D7%A0%D7%9D%D7%A8%D7%95%D7%93/',
    whyThisFits: 'להרגיש כמו אבירים בטירה עתיקה, עם הנוף הכי יפה בצפון.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'c9',
    name: 'נאות קדומים',
    description: 'שמורה של טבע תנ"כי המשחזרת את נופי העבר של ארץ ישראל.',
    region: 'center',
    style: 'history',
    difficulty: 'easy',
    type: 'circular',
    hasFood: false,
    timeAvailable: 'half-day',
    duration: '3 שעות',
    distance: '3 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'הליכה נוחה בשבילים.',
    travelTime: '15 דקות ממודיעין',
    startPoint: 'נאות קדומים',
    endPoint: 'נאות קדומים',
    highlights: ['גתות עתיקות', 'בוסתנים', 'שקט מוחלט'],
    foodRecommendations: ['מסעדות במודיעין'],
    whatToBring: ['מים', 'כובע'],
    season: 'כל השנה (שיא באביב ובחורף)',
    bestTime: 'בוקר',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=נאות+קדומים',
    infoLink: 'https://www.n-k.org.il/',
    whyThisFits: 'טיול של שקט ורוגע בין בוסתנים ונופים של פעם.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'j9',
    name: 'מצפה רמת רחל',
    description: 'מצפה ייחודי המשקיף על ירושלים, בית לחם ומדבר יהודה.',
    region: 'jerusalem',
    style: 'view',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעה',
    distance: '1 ק"מ',
    trailType: 'קווי',
    effortDescription: 'הליכה קלה.',
    travelTime: 'ירושלים',
    startPoint: 'קיבוץ רמת רחל',
    endPoint: 'המצפה',
    highlights: ['פסל עמודי זית', 'נוף פנורמי', 'שלווה של קיבוץ'],
    foodRecommendations: ['קפה ברמת רחל', 'מסעדות בתלפיות'],
    whatToBring: ['מצלמה'],
    season: 'כל השנה',
    bestTime: 'שקיעה',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=מצפה+רמת+רחל',
    infoLink: 'https://www.itraveljerusalem.com/he/attraction/%D7%A4%D7%A1%D7%9C-%D7%A2%D7%9E%D7%95%D7%93%D7%99-%D7%94%D7%96%D7%99%D7%AA/',
    whyThisFits: 'מקום פינתי ופחות מוכר עם נופים עצומים ואווירה מיוחדת.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 's9',
    name: 'נחל חווארים',
    description: 'מסלול לילה קלאסי בתוך קניון חוואר לבן שזורח לאור ירח מלא.',
    region: 'south',
    style: 'nature',
    difficulty: 'easy',
    type: 'short',
    hasFood: false,
    timeAvailable: 'short',
    duration: 'שעתיים',
    distance: '3 ק"מ',
    trailType: 'קווי',
    effortDescription: 'הליכה קלה בירידה.',
    travelTime: 'שלוש שעות מהמרכז',
    startPoint: 'חניון נחל חווארים',
    endPoint: 'גשר נחל חווארים',
    highlights: ['סלע חוואר לבן', 'הליכת ירח מלא', 'שקט מדברי'],
    foodRecommendations: ['פלאפל במדרשת בן גוריון'],
    whatToBring: ['פנס ראש (למקרה הצורך)', 'מים'],
    season: 'סתיו, חורף, אביב',
    bestTime: 'לילות ירח מלא',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=נחל+חווארים',
    infoLink: 'https://www.tiuli.com/tracks/43/%D7%A0%D7%97%D7%9C-%D7%97%D7%95%D7%95%D7%90%D7%A8%D7%99%D7%9D-%D7%94%D7%9C%D7%99%D7%9B%D7%AA-%D7%99%D7%A8%D7%97-%D7%9E%D7%93%D7%91%D7%A8%D7%99%D7%AA-%D7%A7%D7%A1%D7%95%D7%9E%D7%94',
    whyThisFits: 'חוויה של פעם בחיים - ללכת יד ביד בתוך קניון לבן שמאיר את עצמו בתוך המדבר.',
    imageUrl: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'n10',
    name: 'הר ארבל',
    description: 'תצפית מצוקית עוצרת נשימה על הכנרת, הגולן והחרמון, עם ירידה אתגרית בסולמות.',
    region: 'north',
    style: 'view',
    difficulty: 'medium',
    type: 'circular',
    hasFood: false,
    timeAvailable: 'half-day',
    duration: '3 שעות',
    distance: '4 ק"מ',
    trailType: 'מעגלי',
    effortDescription: 'כולל ירידה בסולמות ויתדות במצוק.',
    travelTime: 'שעתיים מהמרכז',
    startPoint: 'חניון גן לאומי ארבל',
    endPoint: 'חניון גן לאומי ארבל',
    highlights: ['תצפית המצוק', 'מבצר המערות', 'נוף פנורמי לכנרת'],
    foodRecommendations: ['מסעדות בטבריה', 'דגי דפנה'],
    whatToBring: ['נעלי הליכה עם אחיזה טובה', 'מים', 'כובע'],
    season: 'חורף, אביב, סתיו',
    bestTime: 'בוקר מוקדם',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=גן+לאומי+ארבל',
    infoLink: 'https://www.parks.org.il/reserve-park/%D7%92%D7%9F-%D7%9C%D7%90%D7%95%D7%9D%D7%99-%D7%95%D7%A9%D7%9E%D7%95%D7%A8%D7%AA-%D7%98%D7%91%D7%A2-%D7%90%D7%A8%D7%91%D7%9C/',
    whyThisFits: 'הכי קרוב להרגשה של לעוף מעל הכנרת - חוויה עוצמתית ומרגשת.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'n11',
    name: 'הר בנטל',
    description: 'אחד המקומות המרשימים בגולן, תצפית אל תוך סוריה בתוך בונקרים משוחזרים.',
    region: 'north',
    style: 'view',
    difficulty: 'easy',
    type: 'short',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעה וחצי',
    distance: '1 ק"מ',
    trailType: 'קווי',
    effortDescription: 'הליכה קלה מאוד על הפסגה.',
    travelTime: 'שלוש שעות מהמרכז',
    startPoint: 'פסגת הר בנטל',
    endPoint: 'פסגת הר בנטל',
    highlights: ['תצפית לסוריה', 'בונקרים צבאיים', 'פסלי מתכת מיוחדים'],
    foodRecommendations: ['קופי ענן (בית קפה על הפסגה)'],
    whatToBring: ['ז׳קט (רוח חזקה כמעט תמיד)', 'מצלמה'],
    season: 'כל השנה (בחורף יש סיכוי לשלג)',
    bestTime: 'צהריים או שקיעה',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=הר+בנטל',
    infoLink: 'https://www.tiuli.com/points-of-interest/43/%D7%94%D7%A8-%D7%91%D7%A0%D7%98%D7%9C',
    whyThisFits: 'שילוב של נוף דרמטי, היסטוריה וקפה טוב בשיא הגובה.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'c10',
    name: 'פארק הרצליה',
    description: 'ריאה ירוקה ומודרנית בלב השרון, עם אגם מלאכותי ודיונות חול משוחזרות.',
    region: 'center',
    style: 'urban',
    difficulty: 'easy',
    type: 'circular',
    hasFood: true,
    timeAvailable: 'short',
    duration: 'שעה וחצי',
    distance: '3 ק"מ',
    trailType: 'מעגלי בפארק',
    effortDescription: 'הליכה מישורית על שבילים סלולים.',
    travelTime: 'הרצליה',
    startPoint: 'פארק הרצליה, כניסה ראשית',
    endPoint: 'פארק הרצליה',
    highlights: ['האגם', 'תצפית הציפורים', 'שבילי אופניים'],
    foodRecommendations: ['בתי קפה בקניון שבעת הכוכבים הסמוך', 'מסעדות בהרצליה פיתוח'],
    whatToBring: ['מחצלת', 'ספר'],
    season: 'כל השנה',
    bestTime: 'אחר הצהריים',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=פארק+הרצליה',
    infoLink: 'https://www.herzliya.muni.il/parkherzliya/',
    whyThisFits: 'דייט קליל ונגיש שתמיד מצליח ליצור אווירה של רוגע בתוך העיר.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop'
  },
  {
    id: 'j10',
    name: 'הר איתן',
    description: 'מסלול הליכה/ריצה פופולרי ומרהיב סביב ההר, המציע נוף אינסופי להרי ירושלים.',
    region: 'jerusalem',
    style: 'nature',
    difficulty: 'medium',
    type: 'circular',
    hasFood: false,
    timeAvailable: 'half-day',
    duration: 'שעתיים וחצי',
    distance: '8 ק"מ',
    trailType: 'מעגלי היקפי',
    effortDescription: 'הליכה ארוכה אך ברובה מישורית סביב ההר.',
    travelTime: '20 דקות מירושלים',
    startPoint: 'חניון הסטף (עליון)',
    endPoint: 'חניון הסטף',
    highlights: ['נוף להרי ירושלים', 'מטעי זיתים', 'אוויר פסגות'],
    foodRecommendations: ['קפה בסטף', 'מסעדות באבו גוש'],
    whatToBring: ['נעלי ספורט', 'הרבה מים'],
    season: 'כל השנה (מדהים בשקיעה)',
    bestTime: 'שקיעה',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=הר+איתן+סטף',
    infoLink: 'https://www.tiuli.com/tracks/114/%D7%A1%D7%91%D7%99%D7%91-%D7%94%D7%A8-%D7%90%D7%99%D7%AA%D7%9F',
    whyThisFits: 'זמן איכות נטו - 8 קילומטרים של שיחה רציפה מול הנוף הכי יפה בהר.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop'
  }
];
